name: signed-commit-action
description: An action that creates signs commits
author: Jan-Otto Kröpke

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: key
  color: orange

# Define your inputs here.
inputs:
  token:
    description: 'GitHub token'
    required: true
  commit_message:
    description: 'Commit message'
    required: true
  target_branch:
    description: 'Branch to commit to'
    required: true

# Define your outputs here.
outputs: {}

runs:
  using: node20
  main: dist/index.js
